# Workflow for validating HTML and CSS
# This workflow runs on pull requests and pushes to ensure code quality

name: Validate Website

on:
  # Runs on pushes targeting any branch
  push:
    paths:
      - "**/*.html"
      - "**/*.css"
      - "**/*.js"
      - "package.json"
      - ".htmlvalidate.json"
      - ".stylelintrc.json"

  # Runs on pull requests
  pull_request:
    paths:
      - "**/*.html"
      - "**/*.css"
      - "**/*.js"
      - "package.json"
      - ".htmlvalidate.json"
      - ".stylelintrc.json"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate:
    name: Validate HTML, CSS, and JavaScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Validate HTML files
        id: validate-html
        run: npm run validate:html
        continue-on-error: true

      - name: Validate CSS files
        id: validate-css
        run: npm run validate:css
        continue-on-error: true

      - name: Check for validation errors
        if: steps.validate-html.outcome == 'failure' || steps.validate-css.outcome == 'failure'
        run: |
          echo "::warning::Validation errors were found. Please check the logs for details."
          if [ "${{ steps.validate-html.outcome }}" == "failure" ]; then
            echo "::error::HTML validation failed"
          fi
          if [ "${{ steps.validate-css.outcome }}" == "failure" ]; then
            echo "::error::CSS validation failed"
          fi
          # Don't fail the workflow, but provide clear warnings
          echo "Validation issues found. These should be fixed before merging."

      - name: Validation summary
        run: |
          echo "## Validation Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ "${{ steps.validate-html.outcome }}" == "success" ]; then
            echo "✅ HTML validation passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ HTML validation failed" >> $GITHUB_STEP_SUMMARY
          fi

          if [ "${{ steps.validate-css.outcome }}" == "success" ]; then
            echo "✅ CSS validation passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ CSS validation failed" >> $GITHUB_STEP_SUMMARY
          fi
